global:

  security:
    authentication:
      method: 'oidc'

  ingress:
    enabled: true
    className: 'nginx'
    annotations:
      cert-manager.io/cluster-issuer: 'letsencrypt-production'
    host: 'camunda8.stackit.gg'
    tls:
      enabled: true
      secretName: 'camunda8-tls'

  identity:
    keycloak:
      url:
        protocol: 'http'
        host: 'camunda-keycloak-service.keycloak.svc.cluster.local'
        port: 8080
      contextPath: '/'
      realm: '/realms/camunda-platform'
      auth:
        adminUser: 'temp-admin'
        existingSecret: 'identity-secret-for-components'
        existingSecretKey: 'identity-keycloak-admin-password'
    auth:
      enabled: true
      publicIssuerUrl: 'https://keycloak.camunda8.stackit.gg/realms/camunda-platform'
      authUrl: 'https://keycloak.camunda8.stackit.gg/realms/camunda-platform/protocol/openid-connect/auth'

      issuerBackendUrl: 'http://camunda-keycloak-service.keycloak.svc.cluster.local:8080/realms/camunda-platform'
      tokenUrl: 'http://camunda-keycloak-service.keycloak.svc.cluster.local:8080/realms/camunda-platform/protocol/openid-connect/token'
      jwksUrl: 'http://camunda-keycloak-service.keycloak.svc.cluster.local:8080/realms/camunda-platform/protocol/openid-connect/certs'
      admin:
        secret:
          existingSecret: 'identity-secret-for-components'
          existingSecretKey: 'identity-admin-client-token'
      identity:
        clientId: 'camunda-identity'

identity:
  enabled: true
  firstUser:
    enabled: true
    username: 'admin'
    email: 'test@test.de'
    firstName: 'Admin'
    lastName: 'User'
    secret:
      existingSecret: 'identity-secret-for-components'
      existingSecretKey: 'identity-first-user-password'
  fullURL: 'https://camunda8.stackit.gg/managementidentity'
  contextPath: '/identity'

identityPostgresql:
  enabled: true
  auth:
    existingSecret: 'identity-secret-for-components'
    secretKeys:
      adminPasswordKey: 'identity-keycloak-postgresql-admin-password'
      userPasswordKey: 'identity-keycloak-postgresql-user-password'

connectors:
  contextPath: '/connectors'
  security:
    authentication:
      oidc:
        secret:
          existingSecret: 'identity-secret-for-components'
          existingSecretKey: 'identity-connectors-client-token'

orchestration:
  contextPath: "/"
  security:
    authentication:
      oidc:
        secret:
          existingSecret: 'identity-secret-for-components'
          existingSecretKey: 'identity-orchestration-client-token'
        redirectUrl: 'https://camunda8.stackit.gg'
    initialization:
      defaultRoles:
        admin:
          users:
            - admin
  ingress:
    grpc:
      enabled: true
      className: 'nginx'
      annotations:
        cert-manager.io/cluster-issuer: 'letsencrypt-production'
      host: 'zeebe.camunda8.stackit.gg'
      tls:
        enabled: true
        secretName: 'camunda8-zeebe-grpc-tls'

  replicas: 1
  clusterSize: "1"
  partitionCount: "1"
  replicationFactor: "1"
  pvcSize: 10Gi

optimize:
  enabled: false


elasticsearch:
  master:
    replicaCount: 1
    persistence:
      size: 10Gi